INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Cole','Alexander','MIDFIELDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nazeer','Allie','DEFENDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Franklyn','Cale','MIDFIELDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lance','Davids','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Keegan','Dolly','MIDFIELDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nathan','Gertse','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Travis','Graham','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thulani','Hlatshwayo','DEFENDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Dominic','Isaacs','DEFENDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Aiden','Jenniker','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Musa Spection','Lebusa','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Cecil','Lolo','DEFENDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mogammed Toriq','Losper','MIDFIELDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lebogang','Manyama','MIDFIELDER',800000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thato','Mokeke','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nathan','Paulse','STRIKER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Brandon','Petersen','GOALKEEPER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Brandon','Peterson','GOALKEEPER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sean','Roberts','GOALKEEPER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Eleazar','Rodgers','STRIKER',750000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Granwald','Scott','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Themba','Shabalala','MIDFIELDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nhlanhla','Shabalala','MIDFIELDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Koen','van de Laak','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Stefan','Van Neel','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ndumiso','Vezi','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Abbubaker','Mobara','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Michael','Kwong','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bantu','Mzwakali','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tashreeq','Morris','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bret','Amidu','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Philani','Cele','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ayanda','Dlamini','STRIKER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sithembiso','Goodman Dlamini','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mkhokheli','Dube','STRIKER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Luyanda','Hlongwa','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mohammed-Awal','Issah','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tapuwa','Kapini','GOALKEEPER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Andile','Khumalo','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bonginkosi','Macala','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kulengani','Madondo','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Njabulo','Manqana','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Aubrey','Mathibe','GOALKEEPER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Phumlani','Mhamha','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thokozani','Mshengu','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nkosinathi','Mthiyane','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Msekeli','Mvalo','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Willem','Mwedihanga','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bongani','Ndulula','STRIKER',800000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Amos Sthembiso','Ngcobo','STRIKER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sthembiso','Ngcobo','STRIKER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Carlington','Nyadombo','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thokozani','Sekotlong','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tamsanqa','Teyise','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Donovan','Thompson','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyabonga','Thwala','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyabonga','Ngubane','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nyiko','Tshabangu','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sydney','Urikhob','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Marc Nathan','Van Heerden','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Philani','Zikalala','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lunga','Zondi','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Letladi','Madubanya','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sfiso','Hlanti','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Larry','Horaed','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mfundo','Nsele','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Emile','Baron','GOALKEEPER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Musa','Junior Bilankulu','DEFENDER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Matthew','Booth','DEFENDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ryan','Chapman','STRIKER',700000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tyrone','Damon','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thembinkosi','Fanteni','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Papy','Faty','MIDFIELDER',700000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sboniso Jomo','Gumede','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Steven','Hoffman','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Erwin','Isaacs','STRIKER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bongolethu','Jayiya','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Moneeb','Josephs','GOALKEEPER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Moeneeb','Josephs','GOALKEEPER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Matome Calvin','Kadi','STRIKER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Letsie','Koapeng','STRIKER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Asive','Langwe','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thapelo Jackson','Mabokgwane','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Conley','Miller','MIDFIELDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sipho','Mngomezulu','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tlau','Molekwane','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Denver','Mukamba','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Benjani','Mwaruwari','STRIKER',750000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ofentse','Nato','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tinashe','Nengomasha','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Denis','Onyango','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Matthew','Pattison','MIDFIELDER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Brad','Phillips','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Katlego','Pule','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Wilko','Risser','STRIKER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ebrahim','Seedat','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sandile','Sibande','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Derick','Spencer','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thomas','Sweswe','DEFENDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kyle','Timm','MIDFIELDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Miquel','Timm','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sibusiso','Vilakazi','MIDFIELDER',700000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kofi','Dankwa','DEFENDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Robin','Ngalande Jr','STRIKER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyabonga','Nhlapo','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sage','Lottering','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Gibeto','Getaneh','STRIKER',4500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'John','Arwuah','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Keegan','Buchanan','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ithumeleng','Duiker','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ruzaigh','Gamildien','MIDFIELDER',750000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lyle','Lakay','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lerato','Lamola','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Auguston','Leonard','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Wandisile','Letlabika','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tsietsi','Mahoa','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tladi','Majake','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lerato','Manzini','STRIKER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thato','Mogakabe','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tumelo','Mogapi','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Joel','Mogorosi','STRIKER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Johannes','Mothlaping','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Roderick','Mutuma','STRIKER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Rodereck','Mutuma','STRIKER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Limbikani','Mzava','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Banele','Ndlovu','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Vuyani','Ntanga','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bennet Thabo','Nthethe','DEFENDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mduduzi','Nyanda','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Musa','Nyatama','MIDFIELDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Khaya','Nzimande','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabani','Stemmer','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Patrick','Tignyemb','GOALKEEPER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Dino','Visser','MIDFIELDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thembalethu','Moses','MIDFIELDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sandile','Ndlovu','STRIKER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Wade','Jooste','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Keamogetse','Wolff','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Daniel','Agyei','GOALKEEPER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mongezi','Bobe','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Daniel','Cardosa','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Coldrin','Coetzee','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Anvar', 'Esterhuyzen','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Soriola','Gege','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mojalefa','Hlahatsi','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Luyanda','Hlongwa','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Angelo','Edwald Kerspuy','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Paulus','Maseshe','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ketlego','Mashego','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thapelo','Mkhatshwa','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tsietsi','Mkwanazi','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Basit','Mohammed','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Basit','Adam','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thapelo','Morweng','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tshepho','Domenic Motsoeneng','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tshepo','Domenic Motsoeneng','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Eric','Mpuqa','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Subusiso','Mthwethwa','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sibusiso','Mthwethwa','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Luyolo','Nomandela','MIDFIELDER',750000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sadate','Ouro Akoriko','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mbhuyiselo','Sambu','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lehlokonolo','Reuben Thebakang','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Danny','Venter','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Enva','Wiltwer','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Themba','Tshabalala','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Moeketsi','Sekola','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bokang Thato','Thlone','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Issa','Sarr','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Camaldine','Abraw','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lucky','Mokoena','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kefuwe','Siyoko','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Rudolf','Bester','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Masonwabe','Bovu','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nkanyiso','Cele','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ricardo','Goss','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Cedric','Gumede','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nkosingiphile','Cedric Gumede','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thanduyise','Khuboni','MIDFIELDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Philani','Kunene','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabiso','Kwela','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mxolisi','Macuphu','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nkanyiso','Madonsela','STRIKER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nkanyiso','Mlotshwa','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siya','Mngoma','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ndabenhle','Mthembu','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Joseph','Musonda','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Jabulani','Innocent Nene','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lucky','Nguzana','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bhekisizwe','Nkosi','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bonginkosi','Excellent Ntuli','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sphesihle ','Nzimande','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nkosinathi','Ogle','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kgotso','Polelo','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Welcome','Qalanto','STRIKER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Philani','Shange','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thembela','Sikhakhane','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siphiwe','Gift Sithole','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siphiwe Gift','Sithole','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Norman','Smith','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mzivukile','Tom','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mzivukile','Sydney Tom','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Peter','Wadabwa','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ntlantla','Zothwane','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Justine','Zulu','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Dumisani','Zwane','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Dumsani','Zwane','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyanda','Zwane','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyanda','Desmond Zwane','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nkanyiso','Mngwengwe','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mandla','Mdunge','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mandla','Mndunge','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siphelele','Hleleni','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siphelele','Mthembu','STRIKER',750000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Luthuli','Nzuzo','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nzuzo','Luthuli','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Luthuli','Siphelele','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lucky','Baloyi','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Josta','Dladla','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siboniso','Gaxa','DEFENDER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lorenzo','Gordinho','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Morgan','Gould','DEFENDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sakhile','Hlongwa','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Jimmy','Jambo','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Willard','Katsande','MIDFIELDER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Itumeleng','Khune','GOALKEEPER',700000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nhlanhla','Khuzwayo','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'George','Lebese','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Reneilwe','Letsholonyane','MIDFIELDER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lehlohonolo','Majoro','STRIKER',750000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mandla','Masango','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tefu','Mashamaite','DEFENDER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tsepo','Masilela','DEFENDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Peter Tsepo','Masilela','DEFENDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Erick','Mathoho','DEFENDER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kgotso','Moleko','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kaizer','Motaung','STRIKER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Simphiwe','Mtsweni','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Knowledge','Musona','STRIKER',950000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nicholas','Mynhardt','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kingston','Nkhatha','STRIKER',700000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kingston','Nkatha','STRIKER',700000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyabonga','Nkosi','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bernard','Parker','STRIKER',1500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Reyaad','Pieterse','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Keegan','Ritchie','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Matthew','Rusike','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lawrence Siphiwe','Tshabalala','MIDFIELDER',1200000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lincoln','Zvayisa','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mumuni','Abubaker','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Wayne','Arendse','DEFENDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Khama','Billiat','MIDFIELDER',1200000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Clayton','Daniels','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Richard','Henyekane','STRIKER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Samuel','Julies','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thato','Kebue','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Hlompho','Kekana','MIDFIELDER',700000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Anthony','Laffor','MIDFIELDER',750000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tebogo','Langerman','DEFENDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tiyani','Mabunda','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Cuthbert','Malajila','STRIKER',1000000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Punch','Masenamela','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mzikayise','Mashaba','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Katlego','Mashego','STRIKER',750000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Emmanuel','Mathias','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), ' Kwanda','Mngonyama','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Teko','Modise','MIDFIELDER',1000000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lebohang','Mokoena','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Raymond','Monama','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bryce','Moon','DEFENDER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Surprise','Moriri','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Katlego','Mphela','STRIKER',700000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kennedy','Mweene','GOALKEEPER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thela','Ngobeni','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Esrom','Nyandoro','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Elias','Pelembe','MIDFIELDER',800000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Rodney','Ramagalela','STRIKER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Wayne','Sandilands','GOALKEEPER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thamsanqa','Sangweni','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Alje','Schut','DEFENDER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Jabulani','Shongwe','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Rashid','Sumaila','DEFENDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Glenn','Verbauwhede','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sename','Dove Wome','MIDFIELDER',800000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Dove','Wome','MIDFIELDER',800000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bongani','Zungu','MIDFIELDER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ramahlwe','Mphahlele','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ramahlwe','Mphahlele','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nicholas','Mlambo','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mohammed','Awal','DEFENDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'David','Booysen','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Delron','Buckley','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ruben','Cloete','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ryan','De Jongh','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Andile','Gabisa','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Frank','Gyamfi','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ashley','Hartog','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Byrone','Hendricks','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Robyn','Johannes','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Terrence','Mandaza','STRIKER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Wayne','Matle','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mlungisi','Mazibuko','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thamsanqa','Mkhize','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Michael','Morton','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Orlando','Smeekes','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Virgil','Vries','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Shu-aib','Walters','GOALKEEPER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Philani','Zulu','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mario','Booysen','DEFENDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Rheece','Evans','DEFENDER',555000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Dillon','Sheppard','MIDFIELDER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mohammed', 'Yakubu','STRIKER',750000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Yakubu','Mohammed','STRIKER',750000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabang','Matuka','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Peter','Petersen','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Heini','Isaacks','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Heini','Isaacks','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tshwarelo','Bereng','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Igor','Bondzulic','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mpho Lerato','Chabangu','MIDFIELDER',800000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Larry','Cohen','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Roger','Da Costa','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Greg','Etafia','GOALKEEPER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ashraf','Hendricks','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Rudi','Isaacs','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Peter Shere','Lekgothoane','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Dikgang','Mabalane','MIDFIELDER',700000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Edward','Manqele','STRIKER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Edward','Mnqele','STRIKER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Gilbert','Mapemba','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Asavela','Mbekile','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Levi','Mokgothu','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Luvhengo','Mungomeni','DEFENDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Giorgi','Nergadze','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyabonga','Nomvethe','STRIKER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Felix','Obada','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lwazi','Skosana','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sage','Stephens','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lefa','Tsutsulupa','MIDFIELDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bongane','Twala','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Darren','Lurie','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Enrico','Adolph','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Eduardo','Soares Ferreira','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Eduardo','Ferreira','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Omar','Hendricks','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mathafane Stanley','Kgatla','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Stanley','Kgatla','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mabhudi Eliott','Khenyeza','STRIKER',700000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mabhuti','Khenyeza','STRIKER',700000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Vincent','Kabola','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Phetolo','Lebepe','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Aleni','Lebyane','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Paulo','Loureiro','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ntuthuko','Mabaso','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Calvin','Marlin','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Dennis','Masina','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Reginald','Mlaba','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Setjhaba','Mmuso','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mazwi','Mncube','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tumelo','Mopedi','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mohou','Motaung','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Esau','Mtsweni','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Asanda','Mvalo','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Method','Mwanjale','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Method','Mwanjali','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sehloho Abia','Nale','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Abia','Nale','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ofentse','Nato','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Eddie','Ngalo','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Zamuxolo','Ngalo','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Clifford','Ngobeni','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bafana','Nhlapo','GOALKEEPER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Themba','Njwaga','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Onyekachi','Okonkwo','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabo','Qalinge','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ryan','Rae','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabang','Rooi','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Phetolo','Sekome','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Junior','Sikiti','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mkhanyiseli','Siwahla','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sibusiso','Themba','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tshidiso','Tukane','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sandile','Zuke','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Themba','Zwane','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Vuyisile','Ntombayithethi','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lennox','Bacela','STRIKER',800000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Fatawu','Dauda','GOALKEEPER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kermit','Erasmus','STRIKER',850000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thamsanqa','Gabuza','STRIKER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ayanda','Gcaba','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mbongeni','Gumede','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Beranger','Itoua','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Andile','Jali','MIDFIELDER',750000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Happy','Jele','DEFENDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Jele','Happy Queenton','DEFENDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Luvuyo','Kelepu','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Daine','Klate','MIDFIELDER',900000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lucky','Lekgwathi','DEFENDER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tshepo','Liphoko','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ndumiso','Mabena','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mabena','Ndumiso Ignacious','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Rooi','Mahamutsa','DEFENDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mahamutsa','Petros Rooi','DEFENDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Terence Mpho','Makola','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Joseph','Malongoane','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Oupa','Manyisa','MIDFIELDER',700000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lehlogonolo','Maselesa','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Cyril','Mashego','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Patrick','Mashele','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Khetowakhe','Masuku','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabo','Matlaba','DEFENDER',750000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Collins','Mbesuma','STRIKER',750000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thulasizwe','Mbuyane','STRIKER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Senzo','Meyiwa','GOALKEEPER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Brighton','Mhlongo','GOALKEEPER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sibusiso','Mnguni','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Molemo Manti','Moholo','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Vusi Simon','Mthimkulu','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sifiso','Myeni','MIDFIELDER',900000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Patrick','Ngidi','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Aubrey','Ngoma','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ntando','Nkala','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sikhumbuzo','Nkumane','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thandani','Ntshumayelo','MIDFIELDER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nhlakanipho','Ntuli','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bheki','Nzunga','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Patrick','Phungwayo','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabo','Rakhale','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyabonga','Sangweni','DEFENDER',750000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tlou','Segolela','MIDFIELDER',750000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'William','Twala','MIDFIELDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyabonga','Zulu','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Henrico','Botes','STRIKER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Takesure','Chinyama','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kabelo','Dambe','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tshepo','Gumede','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sibusiso','Hadebe','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sipho','Jembula','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Vincent','Khumalo','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Michael','Mabule','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Roger','Majafa','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Patrick','Malokase','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Malokase','Molefi Patrick','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Solomon','Mathe','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lindokuhle','Mbatha','MIDFIELDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Vuyo','Mere','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Benson','Mhlongo','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kagiso','Mlambo','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'James','Mofokeng','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Obert','Moyo','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Luvolwethu','Mpeta','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyabonga','Mpontshane','GOALKEEPER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sibusiso','Msomi','STRIKER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabani','Mthembu','STRIKER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Robert','Ng''ambi','MIDFIELDER',850000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mogakolodi','Ngele','MIDFIELDER',900000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ellias Ledile','Ngwepe','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bongani','Nyathi','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ntsikelelo','Nyauza','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Joshua','Sauls','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabiso','Semenya','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tintswalo','Tshabalala','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Rofhiwa','Tshikovhi','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lantshene','Phalane','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Patrick','Molokase','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mothusi','Gopane','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Esau','Kanyenda','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kabelo','Lichaba','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mxolisi','Machupu','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Dibate Prince','Mahlakoane','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Million','Makhubela','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Modiri','Marumo','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thato George','Maselwa','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kgothatso','Mashia','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thapelo Johannes','Mathibe','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Pule','Matlokotsi','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nkueni','Mayala','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nhklakanipho Already','Mkhwanazi','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thobani','Mncwango','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Vukile','Mngqibisa','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tshepo Maxwell','Molala','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Maxwell','Molala','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kekaetswe','Moloi','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Itumeleng','Motsiane','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Galabgwe','Moyana','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Vusi','Mthimkhulu','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sphesihle','Nzimande','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabo','Rakhale','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mirror','Simanyana','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tshepo','Tema','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Puleng','Tlolane','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Chenene','Benett Jerry','MIDFIELDER',800000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bennett','Chenene','MIDFIELDER',800000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mor','Diouf','DEFENDER',700000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sameehg','Doutie','MIDFIELDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Rowen','Fernandez','GOALKEEPER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bevan','Fransman','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mogogi','Gabonamong','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bradley','Grobler','STRIKER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Edwin','Gyimah','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sibusiso','Khumalo','DEFENDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kurt','Lentjies','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'George','Maluleka','MIDFIELDER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Jabulani','Maluleke','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Maluleke', 'Jabulani','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'David','Mathebula','MIDFIELDER',700000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Innocent','Mdledle','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Moffat','Mdluli','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Enocent','Mkhabela','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabo','Moloi','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Clifford','Mulenga','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Morne','Nel','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mame','Niang','STRIKER',1300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'David','Nkausu','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabiso','Nkoana','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Prince','Nxumalo','STRIKER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thuso','Phala','MIDFIELDER',800000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Roscoe','Pietersen','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Boalefa','Pule','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabo','September','DEFENDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Simbashe','Sithole','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ronwen','Williams','GOALKEEPER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sibusiso','Zuma','STRIKER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Aupa','Moeketsi','MIDFIELDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Warren','Bishop','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tristyn','Coetsee','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Gomolemo Grant','Kekana','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Grant','Kekana','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ronald','Ketjijere','MIDFIELDER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ayanda','Lubelo','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Pogiso','Mahlangu','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nkabeng','Maruping','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lucky','Mathosi','STRIKER',650000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mpho','Matsi','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Buhlebuyeza','Mkhwanazi','DEFENDER',550000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tebogo','Monyai','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabo','Mosadi','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Charly','Moussono-Moussono','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Charly','Moussono','DEFENDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyabonga','Ngubani','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lebogang','Ngubeni','GOALKEEPER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Atusaye','Nyondo','STRIKER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ayo','Oluwafemi','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Diphetogo','Selolwane','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Petrus','Shitembi','MIDFIELDER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyabonga','Shoyisa','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Junior','Sibande','DEFENDER',400000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Obidiah','Tarumbwa','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Fikru','Lamessa','STRIKER',500000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Fikru','Teffera','STRIKER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Fikru','Teffera','STRIKER',600000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Arubi','Washington','GOALKEEPER',450000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Washington','Arubi','GOALKEEPER',450000);