INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Soriola Oluwafemi','Gege','DEFENDER',206791);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Maxwell','Molala','MIDFIELDER',131974);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'John','Arwuah','MIDFIELDER',131974);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thapelo Johannes','Mathibe','MIDFIELDER',131974);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lucky','Mokoena','STRIKER',201102);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Fikru','Lamessa','STRIKER',201102);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lehlokonolo','Reuben Thebakang','MIDFIELDER',131974);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Themba','Zwane','MIDFIELDER',131974);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Anthony Snoti','Laffor','STRIKER',201102);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Itumeleng','Motsiane','MIDFIELDER',131974);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nhklakanipho Already','Mkhwanazi','MIDFIELDER',131974);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ndumiso Ignacious','Mabena','STRIKER',201102);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Katlego','Mashego','DEFENDER',206791);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyabonga','Ngubane','STRIKER',201102);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Wandisile','Letlabika','DEFENDER',206791);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Benjani','Mwaruwari','STRIKER',201102);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Abia','Nale','MIDFIELDER',131974);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sean Joseph','Roberts','GOALKEEPER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tashreeq','Morris','STRIKER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Granwald Warren','Scott','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Musa Spection','Lebusa','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Philani Innocent','Zikalala','GOALKEEPER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sandile','Hlanti','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bongi','Macala','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thapelo Jackson','Mabokgwane','GOALKEEPER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Brad Sheldon','Phillips','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Erwin','Isaacs','STRIKER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ryan','Chapman','STRIKER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thembalethu','Moses','GOALKEEPER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sandile','Ndlovu','STRIKER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tumelo Agreement','Mogapi','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Wade','Jooste','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tshepo','Domenic MotsoenengGOA','GOALKEEPER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Angelo','Edwald Kerspuy','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kefuwe','Siyoko','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Moeketsi','Sekola',null,300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nkosingiphile','Cedric Gumede','GOALKEEPER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kgotso','Polelo','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thembela','Sikhakhane','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Masonwabe','Bovu','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nhlanhla Brilliant','Khuzwayo','GOALKEEPER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kgotso','Moleko','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Matthew','Rusike','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lucky Given','Baloyi','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Josta shimane','Dladla','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Wayne','Sandilands','GOALKEEPER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mzikayise','Mashaba','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thamsanqa','Sangweni','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Richard Tebogo','Henyekane','STRIKER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Virgil','Vries','GOALKEEPER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Robyn','Johannes','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Peter Patrick','Petersen','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thokozani Putu','Sekotlong','STRIKER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sage Shane','Lottering','GOALKEEPER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ashraf','Hendricks','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Calvin','Marlin','GOALKEEPER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Stanley','Kgatla','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Zamuxolo','Ngalo','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Clifford','Ngobeni','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Brighton','Mhlongo','GOALKEEPER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mpho','Makola','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lucky','Lekgwathi','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Manti','Moholo','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nicholas','Mlambo',null,300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bongani Sandy','Nyathi','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabani Maluleki','Mthembu','STRIKER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ellias Ledile','Ngwepe','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Rofhiwa','Tshikovhi','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nkueni','Mayala','GOALKEEPER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Million','Makhubela','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Dibate Prince','Mahlakoane','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thato George','Maselwa','STRIKER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Rowen','Fernandez','GOALKEEPER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sibusiso','Khumalo','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mogogi','Gabonamong','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bradley','Grobler','STRIKER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tristyn','Coetsee','GOALKEEPER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Junior Siyabonga','Sibande','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tebogo Reuben','Monyai','DEFENDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Luthuli','Siphelele','MIDFIELDER',300000);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nathan','Paulse','MIDFIELDER',1729);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mxolisi','Machupu','STRIKER',7779);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lance','Davids','MIDFIELDER',14693);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sandile','Sibande','MIDFIELDER',18150);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Edwin','Gyimah','MIDFIELDER',19015);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Gibeto','Getaneh','STRIKER',20743);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sibusiso','Mthwethwa','DEFENDER',20743);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mpho','Matsi','MIDFIELDER',20743);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Vuyani','Ntanga','STRIKER',23336);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ruzaigh','Gamildien','STRIKER',31979);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Koen','van de Laak','MIDFIELDER',31979);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Joseph','Molongoane','STRIKER',31979);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Morgan Leonard','Gould','STRIKER',36301);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Keegan','Buchanan','STRIKER',37165);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nkabeng','Maruping','MIDFIELDER',38029);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Reneilwe','Letsholonyane','MIDFIELDER',39758);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sthembiso','Ngcobo','STRIKER',40622);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lennox','Bacela','STRIKER',41487);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Rodreck','Mutuma','STRIKER',44080);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Robert','Ng''ambi','MIDFIELDER',45808);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabo','Rakhale','MIDFIELDER',48401);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Welcome','Qalanto','MIDFIELDER',50130);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Orlando Dimitri','Smeekes','MIDFIELDER',53587);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nkosinathi','Mthiyane','STRIKER',55315);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kingston','Nkhatha','STRIKER',56180);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sibusiso Njabulo','Msomi','STRIKER',56180);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siphelele Promise','Mthembu','STRIKER',57908);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Puleng Dennis','Tlolane','STRIKER',61366);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ayo','Oluwafemi','STRIKER',62230);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Willard','Katsande','MIDFIELDER',63959);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thamsanqa','Mkhize','STRIKER',69144);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lucky','Mathosi','STRIKER',69144);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ketlego','Mashego','STRIKER',70009);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Felix','Obada','MIDFIELDER',70009);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Danny Wayne','Venter','MIDFIELDER',70873);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ayanda Phelelani','Dlamini','STRIKER',73466);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Obidiah','Tarumbwa','STRIKER',73466);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabo','Qalinge','MIDFIELDER',75194);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Enocent','Mkhabela','DEFENDER',76059);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Aupa','Moeketsi','DEFENDER',78652);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bonginkosi','Excellent Ntuli','STRIKER',82109);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Enva','Wiltwer','STRIKER',83838);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Luyolo','Nomandela','MIDFIELDER',88159);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Vusi','Mthimkulu','DEFENDER',88159);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyabonga Victor','Shoyisa','DEFENDER',88159);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ryan Christopher','De Jongh','MIDFIELDER',89023);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Michael Alan','Morton','MIDFIELDER',90752);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Heini','Isaacks','MIDFIELDER',90752);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sithembiso','Goodman Dlamini','STRIKER',93345);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Matthew','Booth','DEFENDER',94209);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Jabulani','Innocent Nene','MIDFIELDER',95073);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siphiwe Gift','Sithole','DEFENDER',95073);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tshepo','Tema','DEFENDER',95073);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kabelo','Lichaba','DEFENDER',95938);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nzuzo','Luthuli','MIDFIELDER',97666);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Vincent','Kobola','DEFENDER',100259);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Motsere Johannes','Motlhaping','DEFENDER',101124);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Vukile','Mngqibisa','DEFENDER',101124);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Giorgi','Nergadze','MIDFIELDER',102852);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kulengani','Madondo','MIDFIELDER',103717);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Dennis','Masina','STRIKER',108038);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Andile','Jali','MIDFIELDER',112360);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ofentse','Nato','MIDFIELDER',114952);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Matome Calvin','Kadi','STRIKER',115817);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sibusiso','Vilakazi','MIDFIELDER',116681);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mogammed Toriq','Losper','MIDFIELDER',118410);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lunga','Zondi','STRIKER',120138);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tamsanqa','Teyise','DEFENDER',121867);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Edward','Mnqele','MIDFIELDER',127917);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Rudi Charles','Isaacs','DEFENDER',136560);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lehlohonolo Michael','Majoro','STRIKER',139153);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bennet Thabo','Nthethe','MIDFIELDER',140882);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Diphetogo Dipsy','Selolwane','STRIKER',142610);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tshwarelo','Bereng','STRIKER',146067);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabo','Mosadi','MIDFIELDER',146932);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Marc Nathan','Van Heerden','DEFENDER',149525);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Papy','Faty','MIDFIELDER',149525);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bongani','Zungu','STRIKER',150389);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mkhanyiseli','Siwahla','MIDFIELDER',151253);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sphesihle','Nzimande','STRIKER',151253);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sameehg','Doutie','MIDFIELDER',151253);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Knowledge','Musona','STRIKER',152118);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Onyekachi','Okonkwo','STRIKER',152118);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Denver','Mukamba','STRIKER',153846);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Peter Shere','Lekgothoane','DEFENDER',153846);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Daniel','Agyei','GOALKEEPER',154710);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Surprise','Moriri','STRIKER',154710);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mduduzi','Nyanda','STRIKER',154710);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lucky','Nguzana','STRIKER',156439);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Delron','Buckley','MIDFIELDER',157303);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Njabulo','Manqana','STRIKER',158168);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Letladi','Madubanya','MIDFIELDER',159032);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sadate','Ouro Akoriko','DEFENDER',159032);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Collins','Mbesuma','STRIKER',159896);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Auguston Marlon','Leonard','STRIKER',162489);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Basit','Adam','STRIKER',163354);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tsietsi','Mahoa','DEFENDER',164218);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Dumsani','Zwane','MIDFIELDER',167675);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Innocent Thembinkosi','Mdledle','DEFENDER',171997);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Dominic','Isaacs','DEFENDER',176318);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sandile','Zuke','MIDFIELDER',180640);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Charly','Moussono','DEFENDER',181504);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Cecil Sonwabile','Lolo','DEFENDER',182368);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Wayne Earl','Arendse','DEFENDER',185825);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tshepo','Gumede','DEFENDER',186690);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lebogang','Manyama','MIDFIELDER',187554);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Alje','Schut','DEFENDER',187554);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bokane','Tlhone','DEFENDER',188418);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thulani','Hlatshwayo','DEFENDER',192740);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Katlego','Pule','DEFENDER',193604);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mothusi','Gopane','MIDFIELDER',197061);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Paulus Leamoha','Masehe','MIDFIELDER',197926);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Modiri','Marumo','GOALKEEPER',197926);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tinashe Washington','Nengomasha','DEFENDER',200519);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thato Tsiliso','Mokeke','STRIKER',201383);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyanda','Desmond Zwane','DEFENDER',201383);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nhlanhla','Shabalala','MIDFIELDER',202247);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Omar','Hendricks','DEFENDER',206569);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siboniso','Gaxa','DEFENDER',207433);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bongani','Ndulula','STRIKER',208297);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Grant','Kekana','DEFENDER',208297);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Happy','Jele','DEFENDER',211755);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Limbikani','Mzava','DEFENDER',213483);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Patrick Amour','Tignyemb','GOALKEEPER',218669);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mario John','Booysen','DEFENDER',218669);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Asive','Langwe','STRIKER',219533);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Dikgang','Mabalane','STRIKER',222990);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Nkanyiso','Mngwengwe','DEFENDER',226448);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tintswalo Edward','Tshabalala','STRIKER',228176);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ruben','Cloete','DEFENDER',229905);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Oupa Matthews','Manyisa','MIDFIELDER',229905);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Luvolwethu','Mpeta','DEFENDER',233362);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kurt','Lentjies','MIDFIELDER',235091);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Peter Tsepo','Masilela','DEFENDER',236819);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ramahlwe','Mphahlele','STRIKER',237684);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Matthew Joseph','Pattison','MIDFIELDER',240277);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mzivukile','Sydney Tom','DEFENDER',242005);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Asavela','Mbekile','MIDFIELDER',246327);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Msekeli','Mvalo','DEFENDER',250648);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tebogo Joseph','Langerman','DEFENDER',251513);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Willem','Mwedihanga','DEFENDER',255834);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mongezi','Bobe','STRIKER',259291);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mabhuti','Khenyeza','STRIKER',271392);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lefa','Tsutsulupa','MIDFIELDER',272256);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Method','Mwanjale','DEFENDER',283492);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Tefu Junaid','Mashamaite','DEFENDER',284356);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Erick','Mathoho','DEFENDER',285220);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Senzo','Meyiwa','GOALKEEPER',285220);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Solomon','Mathe','MIDFIELDER',287813);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kennedy','Mweene','GOALKEEPER',288678);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Joel','Mogorosi','STRIKER',290406);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Terrence','Mandaza','STRIKER',299049);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ayanda','Gcaba','DEFENDER',299049);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Eduardo','Ferreira','DEFENDER',299914);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Keegan','Dolly','STRIKER',303371);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Keamogetse','Wolff','DEFENDER',305964);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Aiden John','Jenniker','DEFENDER',306828);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyabonga Eugene','Nomvethe','STRIKER',307692);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mor','Diouf','DEFENDER',307692);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bennett','Chenene','MIDFIELDER',310285);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Benson Simphiwe','Mhlongo','DEFENDER',312878);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mandla','Mndunge','DEFENDER',313742);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bryce','Moon','STRIKER',329300);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabo Christopher','September','DEFENDER',332757);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Buhle','Mkhwanazi','DEFENDER',342264);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Rooi','Mahamutsa','DEFENDER',345722);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mohammed','Awal','DEFENDER',347450);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Vuyo Calvin','Mere','DEFENDER',356958);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lindokuhle John','Mbatha','STRIKER',365601);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Washington','Arubi','GOALKEEPER',373379);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Travis Codie','Graham','STRIKER',378565);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Larry Jason','Cohen','DEFENDER',381158);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mogakolodi Lucky','Ngele','STRIKER',387208);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Brandon','Peterson','GOALKEEPER',398444);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Luvhengo','Mungomeni','DEFENDER',399309);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'William','Twala','STRIKER',407087);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thabo','Matlaba','DEFENDER',407952);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Teko Tsholofelo','Modise','MIDFIELDER',415730);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Thuso','Phala','MIDFIELDER',418323);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Shu-Aib','Walters','GOALKEEPER',429559);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'David','Mathebula','STRIKER',433016);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Hlompho Alpheus','Kekana','MIDFIELDER',434745);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lyle','Lakay','STRIKER',439931);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Cuthbert','Malajila','STRIKER',452031);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siya Mpande','Mngoma','GOALKEEPER',484875);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Yakubu','Mohammed','STRIKER',493518);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Itumeleng isaack','Khune','GOALKEEPER',496111);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bafana','Nhlapo','GOALKEEPER',496111);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Bernard Melvin','Parker','STRIKER',506482);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Ronwen Hayden','Williams','GOALKEEPER',508211);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Peter','Wadabwa','STRIKER',516854);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Kermit','Erasmus','STRIKER',523768);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Rheece','Evans','DEFENDER',529818);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Lawrence Siphiwe','Tshabalala','STRIKER',541919);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Dove','Wome','STRIKER',567848);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Sifiso','Myeni','STRIKER',568712);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siphelele','Hleleni','MIDFIELDER',594641);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Moneeb','Josephs','GOALKEEPER',598099);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Dillon','Sheppard','MIDFIELDER',608470);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mame','Niang','STRIKER',725151);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Siyabonga','Mpontshane','GOALKEEPER',746759);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Greg','Etafia','GOALKEEPER',870354);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Aubrey','Mathibe','GOALKEEPER',906655);
INSERT INTO game_player_price(id, first_name, last_name, block, price) VALUES((select nextval('player_price_seq')), 'Mpho Lerato','Chabangu','STRIKER',1000000);